backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true
  commit_messages:
    create: ":sparkles: Create {{collection}} > {{slug}}"
    update: ":pencil2: Update {{collection}} > {{slug}}"
    delete: ":fire: Delete {{collection}} > {{slug}}"
    uploadMedia: ":bento: Upload {{path}}"
    deleteMedia: ":fire: Delete: {{path}}"
  accept_roles: #optional - accepts all users if left out
    - root

publish_mode: editorial_workflow

# media_folder: "static/assets/img/uploads" # Media files will be stored in the repo under static/assets/img/uploads
# public_folder: "/assets/img/uploads" # The src attribute for uploaded media will begin with /assets/img/uploads

# back office
site_url: https://poc-netlify-cms.netlify.com
display_url: https://poc-netlify-cms.netlify.com
logo_url: http://poc-netlify-cms.netlify.com/assets/img/admin_logo.svg

# enable to display preview links
show_preview_links: true

# slug
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: "_"

# collections
collections:
  - name: pages
    label: Pages
    label_singular: Page
    description: "Static pages of the website"
    extension: json
    format: json
    files:
      - name: index
        label: Home
        file: ".content/pages/index.json"
        fields:
          - { name: title, label: Title, widget: string }
          - { name: punchline, label: Punchline, widget: text }
          - {
              name: featured,
              label: "Featured Blog Post",
              widget: relation,
              collection: blog,
              searchFields: [title, punchline],
              valueField: title,
              displayFields: [title],
            }

  - name: blog
    label: Blog Posts
    label_singular: Blog Post
    description: Basic blog posts
    folder: ".content/posts/blog"
    extension: json
    format: json
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    preview_path: "blog/{{slug}}"
    fields:
      - { name: date, label: "Publish Date", widget: date, format: L }
      - { name: title, label: Title, widget: string }
      - {
          name: featured_image,
          label: "Featured image",
          widget: "image",
          media_library: { config: { multiple: false } },
        }
      - { name: lead, label: Lead Paragraph, widget: text }
      - { name: body, label: Body, widget: markdown }
    summary: "{{title}} | {{lead}}"
