backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true
  commit_messages:
    create: ":sparkles: create {{collection}} > {{slug}}"
    update: ":pencil2: update {{collection}} > {{slug}}"
    delete: ":fire: delete {{collection}} > {{slug}}"
    uploadMedia: ":bento: upload {{path}}"
    deleteMedia: ":fire: delete: {{path}}"
  accept_roles: #optional - accepts all users if left out
    - root

publish_mode: editorial_workflow

# media_folder: "static/assets/img/uploads" # Media files will be stored in the repo under static/assets/img/uploads
# public_folder: "/assets/img/uploads" # The src attribute for uploaded media will begin with /assets/img/uploads

# back office
site_url: https://template-netlify-cms.netlify.com
display_url: http://template-netlify-cms.netlify.com
logo_url: http://localhost:3000/assets/img/admin_logo.svg

# enable to display preview links
show_preview_links: false

# slug
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

# collections
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    description: "Static pages of the website"
    files:
      - name: "index"
        label: "Home"
        file: ".content/pages/index.json"
        fields:
          - { label: Title, name: title, widget: string, required: true }
          - { label: Punchline, name: punchline, widget: text }
          - { label: Content, name: body, widget: markdown }

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Posts" # Used in the UI
    label_singular: "Blog Post"
    description: "Basic blog posts"
    folder: ".content/posts/blog" # The path to the folder where the documents are stored
    extension: "json"
    format: "json"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: Punchline, name: punchline, widget: text }
      - { label: "Body", name: "body", widget: "markdown", required: true }

  - label: "Blog in English"
    name: "english_posts"
    folder: ".content/posts/test"
    filter: { field: "language", value: "en" }
    fields:
      - {
          label: "Language",
          name: "language",
          widget: "select",
          options: ["en", "es"],
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content", name: "body", widget: "markdown" }

  - label: "Blog en Español"
    name: "spanish_posts"
    folder: ".content/posts/test"
    filter: { field: "language", value: "es" }
    fields:
      - {
          label: "Lenguaje",
          name: "language",
          widget: "select",
          options: ["en", "es"],
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }
